elementary:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: "{{ env_var('DB_USER', 'lambda2') }}"
      password: "{{ env_var('DB_PASS', 'lambda2') }}"
      port: 5432
      dbname: datalab
      schema: bronze

datalab:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: datalab
      password: datalab
      port: 5432
      dbname: datalab
      schema: bronze
      threads: 4